apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: production-eks
  region: <aws-region>

iam:
  withOIDC: true

vpc:
  subnets:
    private:
      <aws-az-1>: { id: <subnet-id> }
      <aws-az-2>: { id: <subnet-id> }
      <aws-az-3>: { id: <subnet-id> }

nodeGroups:
  - name: production-workers
    instanceType: m5.large
    desiredCapacity: 3
    ssh:
      allow: true
      publicKeyName: <update-ec2-keyname-here>
