Description:  This template deploys a two EC2 instances as bastion hosts with all the utilities.

Mappings:
  RegionMap:
    us-east-1:
      "HVM": "ami-00e87074e52e6c9f9"
    us-west-1:
      "HVM": "ami-0bdb828fd58c52235"
    us-east-2:
      "HVM": "ami-00f8e2c955f7ffa9b"
    us-west-2:
      "HVM": "ami-0686851c4e7b1a8e1"

Parameters:
  vpcName:
    Description: VPC ID for the management VPC
    Type: String
    Default: vpc-085833422fed3797b
  keyPairName:
    Description: Key pair name (if there is no existing key pair then create one)
    Type: String
    Default: oregon
  publicMgmtSubnet1:
    Description: Public Subnet from Management VPC
    Type: String
    Default: subnet-05f153cfceef2d1bf
  publicMgmtSubnet2:
    Description: Public Subnet from Management VPC
    Type: String
    Default: subnet-05f153cfceef2d1bf

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow SSH to bastion host
        GroupName: bastionhostSG
        VpcId: !Ref vpcName
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  Ec2Instance1:
    Type: AWS::EC2::Instance
    DependsOn: [InstanceSecurityGroup]
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
          - "RegionMap"
          - Ref: "AWS::Region"
          - "HVM"
      KeyName: !Ref keyPairName
      Tags:
        - Key: Name
          Value: BastionHost
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo yum install -y unzip
          sudo yum install -y git
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
          echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
          chmod 700 get_helm.sh
          ./get_helm.sh
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: [!Ref InstanceSecurityGroup]
          SubnetId: !Ref publicMgmtSubnet1

  Ec2Instance2:
    Type: AWS::EC2::Instance
    DependsOn: [InstanceSecurityGroup]
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
          - "RegionMap"
          - Ref: "AWS::Region"
          - "HVM"
      KeyName: !Ref keyPairName
      Tags:
        - Key: Name
          Value: BastionHost
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo yum install -y unzip
          sudo yum install -y git
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
          echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
          chmod 700 get_helm.sh
          ./get_helm.sh
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: [!Ref InstanceSecurityGroup]
          SubnetId: !Ref publicMgmtSubnet2
